export const ACTIVITY_EVENT_TYPES = [
  "open_app",
  "choose_category",
  "start_analysis",
  "view_recommendation",
  "bookmark_code",
  "open_profile",
  "start_interview",
  "finish_interview",
  "generate_plan",
  "save_plan",
  "complete_plan_step",
  "test_plan",
  "complete_plan",
  "regenerate_plan",
  "use_teacher",
  "coach_goal_set",
  "coach_diagnostic_taken",
  "coach_roadmap_created",
  "coach_day_completed",
  "coach_task_completed",
  "coach_mini_test_taken",
  "coach_streak_milestone",
  "coach_goal_achieved",
] as const

export type ActivityEventType = (typeof ACTIVITY_EVENT_TYPES)[number]

export const ACTIVITY_EVENT_LABELS: Record<ActivityEventType, string> = {
  open_app: "Запуск приложения",
  choose_category: "Выбор направления",
  start_analysis: "Запуск анализа",
  view_recommendation: "Просмотр рекомендации",
  bookmark_code: "Сохранение кода в закладки",
  open_profile: "Открытие профиля",
  start_interview: "Начало AI-собеседования",
  finish_interview: "Завершение AI-собеседования",
  generate_plan: "Генерация плана развития",
  save_plan: "Сохранение плана",
  complete_plan_step: "Выполнение шага плана",
  test_plan: "Тестирование плана",
  complete_plan: "Завершение плана развития",
  regenerate_plan: "Регенерация плана",
  use_teacher: "Общение с AI Teacher",
  coach_goal_set: "Установка цели в Coach",
  coach_diagnostic_taken: "Прохождение диагностики",
  coach_roadmap_created: "Создание Roadmap",
  coach_day_completed: "Завершение дня",
  coach_task_completed: "Выполнение задачи",
  coach_mini_test_taken: "Прохождение мини-теста",
  coach_streak_milestone: "Достижение streak",
  coach_goal_achieved: "Достижение цели",
}
